name: docs

on:
  - push

permissions:
  contents: write

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project and environment
        uses: ./.github/actions/setup-project

      - name: Build documentation
        run: uv run --no-sync poe doc

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
