name: tests

on:
  - push

jobs:
  tests:
    name: Tests on ${{ matrix.os }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.13"
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project and environment
        uses: ./.github/actions/setup-project
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run --no-sync poe test
